Création d'un timer
CHUMneuroepilepsie/VR_Polytechnique pull request #11
Opened 2022-10-04 04:24 UTC by lulubou

### Checklist

- [*] J'ai donné un titre significatif
- [*] J'ai décrit la modification
- [*] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:

Ajout d'un script pour faire fonctionner un stopwatch, devrait fonctionner. Ajout de boutons de début et de fin de stopwatch dans le menu anglais (seulement pour tester), mais ne sont pas encore reliés à son fonctionnement. Il devrait être possible d'utiliser le stopwatch en ce moment, mais je n'arrive pas à relier son fonctionnement à un GameObject de texte pour afficher le temps et le tester. Tout devrait fonctionner une fois ce bug résolu.

2022-10-04 21:32 UTC, YassineDiouri1 commented
Je suis pas sur de comprendre c'est quoi le problème. Quand je lance MenuAnglais je vois le start, le stop et le timer fonctionne bien.

2022-10-18 03:41 UTC, lulubou commented
Avec mon dernier commit, le timer fonctionne bien et les scènes de fin (menus) sont fonctionnelles avec les autres scènes. J'ai encore des problèmes avec des erreurs de "Reference to an object" qui n'existe pas, mais ça n'affecte en rien le fonctionnement du jeu, je ne comprends pas...

2022-10-18 13:19 UTC, 4rnaudB requested changes

2022-10-18 13:19 UTC, 4rnaudB commented on VR_Polytechnique/Assets/Scripts/MenuManager.cs
> +        currentTimeText.text = PlayerPrefs.GetString("Time");
Cette ligne référence un objet, mais sa référence n'est pas indiqué dans Unity, d'où l'erreur. Le jeu peut rouler pcq tu n'utilises pas cet objet dans le menu puisque tu n'affiches plus le temps de jeu.

2022-10-19 12:12 UTC, 4rnaudB approved these changes

2022-10-19 15:13 UTC, merged