<Fonctionnalité de mouvement dans la scene base et délétion de la scene Camera&Mouvement>
CHUMneuroepilepsie/VR_Polytechnique pull request #12
Opened 2022-10-04 21:56 UTC by YassineDiouri1

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:

Suppression de la scène Camera&Mouvement et ajout de la feature de mouvement dans la scène  Base .

Attendre de tester la feature avec le casque VR avant de pull

2022-10-08 14:20 UTC, 4rnaudB commented
@YassineDiouri1 Update?

2022-10-08 19:07 UTC, YassineDiouri1 commented
Pas encore fait , j'ai pas eu le temps avec des remises, je fais ca demain

2022-10-15 22:50 UTC, YassineDiouri1 commented
Fonctionnel avec le casque HTC Vive et les deux controlleurs

2022-10-15 23:24 UTC, 4rnaudB reviewed
Voir en dessous

2022-10-18 13:20 UTC, 4rnaudB requested changes
Fixer les conflits

2022-10-20 16:20 UTC, 4rnaudB commented
On est obligé d'afficher ça?
![image](https://user-images.githubusercontent.com/55560824/197004117-fedeb772-2da9-40f9-8e80-c270e9ef0814.png)

2022-10-20 16:25 UTC, YassineDiouri1 commented
> On est obligé d'afficher ça? ![image](https://user-images.githubusercontent.com/55560824/197004117-fedeb772-2da9-40f9-8e80-c270e9ef0814.png)

Nop je vais l'enlever

2022-10-20 16:31 UTC, YassineDiouri1 commented
Tu peux retester ca devrait etre bon

2022-10-20 16:33 UTC, 4rnaudB approved these changes

2022-10-20 16:34 UTC, merged