Ajout d'objets et correction des emplacements
CHUMneuroepilepsie/VR_Polytechnique pull request #123
Opened 2023-03-26 17:48 UTC by FatimaGharsallah

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
J'ai gardé seulement 20 spawners et je les ai placés au milieu du chemin. J'ai rajouté 4 objets (pour avoir un total de 20), une fourchette, une cuillère, un livre et un marteau. J'ai corriger trousse de premiers soins.

@gabygabou Tu pourras partir de cette branche pour faire tes changements!

#118

2023-03-27 23:10 UTC, 4rnaudB requested changes
Les objets ne sont pas de la bonne grosseur et tu as déplacé les spawners mais tu devrais simplement placer l'objet directement à cet endroit.

2023-03-28 19:41 UTC, gabygabou commented
Oui vu que Amélie a dit que tous les objets doivent apparaitre dans le même ordre et au même endroit pour tous les patients, on peut supprimer tous les spawners et juste placer les objets aux endroits qu'on veut @FatimaGharsallah @4rnaudB

2023-03-28 20:31 UTC, YassineDiouri1 commented
Pour le box collider, vu que l'objet est tres petit, ca change pas enormement la marge d'erreur pour cliquer dessus, est ce que tu pourrais manuellement augmenter la taille des collider? @gabygabou

2023-03-29 01:40 UTC, gabygabou commented
@YassineDiouri1 Je peux faire ça oui, pour l'instant je vais doubler chaque dimension des colliders mais ça se peut qu'ils soient trop grands comme ça, on fera des tests pour trouver la taille optimale des colliders

2023-03-29 01:57 UTC, FatimaGharsallah commented
@gabygabou stp prochaine fois, tu me diras si tu vas travailler sur ma branche, pcq là on a essayé de push en même temps et j'ai eu des conflits de mon bord!

2023-03-29 01:58 UTC, gabygabou commented
@FatimaGharsallah Ah scuse my bad

2023-03-30 23:20 UTC, 4rnaudB commented
@FatimaGharsallah tu n'as pas rajouté le script saveObjects au nouvel objet qui remplace spawners, fais attention de garder les scripts importants

2023-04-03 22:40 UTC, YassineDiouri1 commented
Les objets sont pas ceux qui ont un BoxCollider faut les remplacer par les nouveaux.

2023-04-05 16:42 UTC, merged