Terrain creation, separation, added grass texture and trail for forest
CHUMneuroepilepsie/VR_Polytechnique pull request #15
Opened 2022-10-08 22:46 UTC by FatimaGharsallah

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
**Création du terrain:**

- Division des scènes en 2 (une pour mode évaluation et l'autre pour mode apprentissage)
- Téléchargement de terrain tools, d'un assets pour les textures de terrain et des assets pour le ciel
- Ajout d'un ciel et changement au niveau de la lumière directionnelle
- Ajout de reliefs et de textures sur la partie forêt
- Traçage du chemin de la partie forêt
- Séparation du terrain en 4 et chaque partie a été inclue dans les prefabs respectifs

2022-10-09 00:48 UTC, 4rnaudB requested changes
Tu as un fichier New Terrain qui n'est pas dans un fichier désigné. S'il est inutile, le delete, sinon, sûrement le mettre dans Design/Terrain/ ?

2022-10-09 00:50 UTC, 4rnaudB commented
Aussi il y a vraiement beaucoup de nouveaux fichier, si tu peux en delete (Demo, Cartoon peut-être?)

2022-10-11 15:26 UTC, FatimaGharsallah commented
J'ai supprimé les fichiers inutiles (surtout les ciels et textures qu'on n'allait pas utiliser). Il y en a dont je n'étais pas sûre donc je les ai gardés. Sinon je pensais créer une autre branche juste pour rajouter tous les assets qu'on va utiliser pour forêt. C'est mieux de créer une autre branche ou je le fais dans celle-là, puisque je vais juste importer des assets ?

2022-10-11 15:33 UTC, 4rnaudB approved these changes

2022-10-11 17:01 UTC, merged