Ajout des assets utiles pour le design de la foret
CHUMneuroepilepsie/VR_Polytechnique pull request #23
Opened 2022-10-14 05:05 UTC by FatimaGharsallah

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
Ajout des assets utiles pour la forêt:
- Conifers
- Roches
- Textures sols
- Fleur
- Gazon
- Objets utiles (ponts, bateau, banc de parc)

2022-10-16 17:40 UTC, FatimaGharsallah commented
Je viens d'enlever plusieurs fichiers inutiles. Il y en a quelques-uns dont je n'étais pas sûre, donc je les ai gardés.

2022-10-18 13:29 UTC, 4rnaudB approved these changes
On devrait être correct en terme de bandwith si on a presque toutes les assets dans ce merge ^^

2022-10-18 14:35 UTC, 4rnaudB requested changes
Les fichiers dans VR_Polytechnique/Assets/Design/Conifers [BOTD]/ de type .meta sont supprimés à l'ouverture du jeu.

2022-10-18 14:42 UTC, 4rnaudB commented
S'ils ne sont pas nécessaires, simplement les delete, mais si quand toi tu ouvres le jeu ils restent intact, il faut vérifier ce qu'il se passe.

2022-10-18 17:54 UTC, EmmanuelDW commented
Selon ce que j'ai lu il faut inclure les files .meta dans les push parce que unity s'en sert pour créer des liens avec les assets placé dans le jeu. S'il on les supprime avant de push, unity va les recréer automatiquement, mais le contenu du file sera pas exactement le même et ça risque de créer des erreurs éventuellement. Si on le mets en .gitignore, ça risque de créer le même problème, mais parce que le contenu sera pas à jour.

En gros, on a sans doute pas le choix de les laisser se faire push à chaque fois.

2022-10-18 18:56 UTC, EmmanuelDW reviewed
Je laisserais les .meta se faire push pour éviter des bugs futurs. Par contre, il faudrait peut-être mettre tout le contenu des fichiers d'assets en LFS pour éviter que le repo devienne trop gros à force de créer des nouvelles versions ??

2022-10-18 18:58 UTC, 4rnaudB commented
> Selon ce que j'ai lu il faut inclure les files .meta dans les push parce que unity s'en sert pour créer des liens avec les assets placé dans le jeu. S'il on les supprime avant de push, unity va les recréer automatiquement, mais le contenu du file sera pas exactement le même et ça risque de créer des erreurs éventuellement. Si on le mets en .gitignore, ça risque de créer le même problème, mais parce que le contenu sera pas à jour.
> 
> En gros, on a sans doute pas le choix de les laisser se faire push à chaque fois.

Le problème c'est que les fichiers existent, mais quand tu ouvres Unity, ils sont automatiquements supprimés. si tu fermes Unity et ouvre à nouveau, ils ne sont pas recréés.

2022-10-20 01:51 UTC, FatimaGharsallah commented
Personnellement, quand j'ouvre le jeu (unity), je ne remarque pas l'erreur. Les meta files sont encore dans le dossier. 
![image](https://user-images.githubusercontent.com/80424041/196837288-730e2fb9-26b5-41ff-b973-45b6953c5b76.png)

2022-10-20 12:29 UTC, 4rnaudB commented
@lulubou @YassineDiouri1 est-ce que vous pouvez tester a branche svp

2022-10-20 13:48 UTC, ReiherL commented
Ouais si @YassineDiouri1 ou @lulubou vous pouvez aussi vérifier ça serait bien pcq je (Fatima) suis sur l'ordi de Ke et ça fonctionne aussi quand je vérifie avec le compte de lauriane.
![image](https://user-images.githubusercontent.com/113786488/196966634-7a35411c-68e2-4b20-a752-c305f1a94355.png)

2022-10-20 16:04 UTC, YassineDiouri1 commented
![image](https://user-images.githubusercontent.com/113944605/197000385-2b4186d7-c4b0-42bd-b924-14aeefbec972.png)
quand j'ouvre unity j'ai pas d'erreur mais quand je change de la scene ModeApprentissage à ModeEvaluation ca me les donnes

2022-10-23 01:59 UTC, FatimaGharsallah commented
J'ai enlevé les quatre fichiers de Conifer [BOTD]. On n'en n'a plus vraiment besoin, mais je voulais les garder au cas où. Sinon, pour le fichier de flooded grounds, je l'ai supprimé et réimporté, mais ça n'a pas été reconnu dans le commit, donc je ne suis pas sûre que ça a réglé le problème. De ce que j'ai compris le bug affectait seulement ces cinq fichiers, donc ça devrait être correcte.

2022-10-23 14:18 UTC, 4rnaudB commented
@FatimaGharsallah Essaye pour voir maintenant. Après mon commit je n'ai plus de problèmes.

2022-10-23 14:40 UTC, FatimaGharsallah commented
@4rnaudB ça marche pour moi aussi (pas de changements dans git status)!

2022-10-23 17:25 UTC, 4rnaudB commented
@YassineDiouri1 toi ça donne quoi?

2022-10-24 01:30 UTC, YassineDiouri1 commented
Ca marche pour moi aussi

2022-10-24 01:32 UTC, 4rnaudB approved these changes

2022-10-24 02:11 UTC, merged