Ajout d'un relief et d'arbre en background
CHUMneuroepilepsie/VR_Polytechnique pull request #26
Opened 2022-10-24 15:43 UTC by EmmanuelDW

### Checklist

- [x] J'ai donné un titre significatif
- [x] J'ai décrit la modification
- [x] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
Ajout d'un prefab contenant 12 tuiles qui entourent les 4 quadrants du jeu. Les tuiles sont créé de manière s'ajuster automatiquement au changement de relief des tuiles voisines afin d'éviter les gap. Ces tuiles ont un relief élevé, afin que le joueur ne puisse pas percevoir la frontière du jeu. Elles sont aussi recouverte d'arbre pour ne pas nuire au réalisme.

![image](https://user-images.githubusercontent.com/55562569/197568066-5b083dbb-7bba-49cc-8ecd-6ce166b93cfd.png)

2022-10-28 01:50 UTC, FatimaGharsallah requested changes
En général c'est bon, mais il y a quelques petits problèmes. Premièrement, quand j'ouvre Unity, j'ai des erreurs au niveau des shaders.
![image](https://user-images.githubusercontent.com/80424041/198446011-651db288-e332-4530-bb9f-2c1c4b0d639f.png)
Aussi, quand je clique play, je n'ai plus accès à la vue du joueur (donc à la caméra du joueur). (Ce n'est peut-être pas lié à ta PR)

Sinon, au niveau design je réduirais un peu la hauteur et la raideur de quelques montagnes, parce que j'ai peur qu'on les voient par dessus les arbres qui vont être proches.
![image](https://user-images.githubusercontent.com/80424041/198448179-fd34c391-5f44-4ce6-ac28-34db36086183.png)

2022-10-28 23:21 UTC, EmmanuelDW commented
TLDR : Les bugs présent l'était déjà lorsque j'ai démaré ma branche donc ça devrait être safe de faire le merge. Il faudra parcontre régler quelques petites bug/défauts dans le futur.

J'ai smooth les montagnes et refait les arbres pour avoir une meilleure densité et diversité. J'ai ajouté un group LOD avec les mêmes configs à chaque tuiles de la scène. J'ai corriger des gap qu'on avait entre nos sections.

Les erreurs de shader étaient déjà présent dès que j'ai ouvert ma branch, mais elles semblent avoir disparues par elles même. Peut-être que si la deuxième fois que tu vas ouvrir ma nouvelle version ça sera fix. 

Sinon j'ai trouvé des problèmes qui relèvent pas trop de ce que j'ai ajouté, mais du projet en général :
1. Le FPS est pas mal bas, genre 20 FPS, peut-être qu'en jouant avec le LOD ça va s'améliorer (j'ai été pas mal généreux dans avec la distance max pour les meshs les plus détaillés)
2. Malgré une distance de culling plus grande que la taille de la scène, (distance à laquelle les assets disparaissent complètement), on peut voir que les arbres disparaissent à une certaine distance.
3. Le timer fait une erreur parce qu'il essait d'accèder à l'index d'un array qui est plus grand que la taille de l'array.
4. Le déplacement de la caméra du personnage est difficile a faire parce que le groupe qui inclu la camera et les mains du personnage ne sont pas à la même position alors on ne sait pas ou la camera va se trouver lorsqu'on déplace le groupe. 

Les 3 premiers problèmes peuvent être vue ici 
![image](https://user-images.githubusercontent.com/55562569/198749194-d473c1c9-3278-45bc-9c7e-bac9c2aa8453.png)

2022-10-30 02:19 UTC, FatimaGharsallah commented
Dernier petit commentaire. Je pense qu'en faisant le relief du côté, tu as rajouté quelques bosses sur le terrain. Il y en a qui sont sur le chemin et qui sont très élevées. Je les réduirais un peu. 

Voici quelques examples:
Terrain_FG
![image](https://user-images.githubusercontent.com/80424041/198859540-3b75eb51-68ce-46ca-ba76-05e1497f5a0a.png)
Terrain_LG
![image](https://user-images.githubusercontent.com/80424041/198859568-c7270b17-23d4-4308-9146-ce31ddb6e01b.png)

Ici il est supposé y avoir un lac, donc aucun relief (Terrain_AS)
![image](https://user-images.githubusercontent.com/80424041/198859560-36455765-613d-4f39-bf44-442822a2b2c0.png)

2022-10-30 20:26 UTC, FatimaGharsallah approved these changes

2022-10-30 20:50 UTC, merged