Sous-menu pour avoir le choix de la difficulté et de l'usager
CHUMneuroepilepsie/VR_Polytechnique pull request #27
Opened 2022-10-25 05:03 UTC by lulubou

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modification:

Ajout d'un sous-menu lors de l'appui du bouton de démarrage d'un essai de test (et non tutoriel). Voici à quoi ressemble le menu, avec deux listes déroulantes pour les deux paramètres.
![image](https://user-images.githubusercontent.com/80421345/197686087-90b52f45-db7e-435f-b12c-29d0805e6931.png)

Il est possible de remplir la liste déroulante dans un script avec des valeurs prises ailleurs (banque de donnée .json, par exemple). Par contre, j'ai bûché et suivi des tutoriels pour le faire et je n'y arrivais pas, j'avais toujours une erreur, donc j'ai effacé les fichiers en lien avec ça, et on pourra regarder ça ensemble @4rnaudB.

J'ai aussi sauvé la valeur de la difficulté dans le fichier .json _Settings_. Il pourrait être pertinent de faire un menu permettant de choisir la difficulté pour le tutoriel aussi, à bien y penser, parce qu'il serait important que le patient commence à la même place où il s'est entraîné.

2022-10-25 14:50 UTC, 4rnaudB requested changes
Ajouter le menu en français pcq ça cause des bugs quand tu utilises le menu français

2022-10-25 23:57 UTC, lulubou commented on VR_Polytechnique/Assets/Scripts/MenuScripts/LevelDropdown.cs
> +using System.Collections;
Oui ça serait mieux je pense, mais j'suis pas certain

2022-11-03 15:52 UTC, 4rnaudB requested changes

2022-11-03 15:52 UTC, 4rnaudB commented on VR_Polytechnique/Assets/Scripts/MenuScripts/LevelDropdown.cs
> +        }
```suggestion

```

2022-11-03 15:55 UTC, 4rnaudB approved these changes

2022-11-03 15:59 UTC, merged