checkpoints 5 et 6 première version
CHUMneuroepilepsie/VR_Polytechnique pull request #34
Opened 2022-11-07 18:55 UTC by ReiherL

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
Les checkpoints 5 et 6 sont faits, mais relativement grossièrement et seront à peaufiner.

2022-11-08 00:09 UTC, FatimaGharsallah requested changes
Naviguer à travers tes checkpoints est très "laggy". De ce que j'ai vu, c'est vraiment à cause du gazon mis. Il y en a beaucoup à des endroits pas vraiment nécessaires. Alors, commence par enlever le gazon et regarde si ça bogue encore, puis place du gazon seulement proche du sentier. Aussi, il y a quelques peaufinements à apporter (quelques arbres dans le chemin et au premier checkpoint, il est possible de voir qu'un chemin est bloqué)

2022-11-09 20:27 UTC, ReiherL commented
conflit à régler, supprimer le terrain de fatima (0_0), mais garder les terrain data

2022-11-10 20:59 UTC, 4rnaudB commented
@ReiherL Vérifie que mes modifications n'ont pas enlevé quelque chose d'imprtant. @FatimaGharsallah tu peux vas pouvoir vérifier que les modifs que tu voulais sont là.

2022-11-13 18:50 UTC, ReiherL commented
@4rnaudB Ça n'a rien enlevé mais j'ai encore des conflits avec des TerrainData...

2022-11-13 18:54 UTC, 4rnaudB commented
Étrange l'autre jour il n'y avait plus de conflits

2022-11-13 19:33 UTC, ReiherL commented
J'ai rien push depuis que t'as fait les changements, feck je sais pas d'ou ils viennent

2022-11-15 20:32 UTC, ReiherL commented
@FatimaGharsallah les conflits sont réglés, can u approve plize

2022-11-15 21:23 UTC, FatimaGharsallah commented
J'ai apprové ta pr, mais il va avoir des trucs à peaufiner. Tu as du gazon bleu, il faudra ajuster ça prochainement et sur cette photo, le chemin du milieu est en pointillé.
![image](https://user-images.githubusercontent.com/80424041/202028164-8b544ccb-ff35-47b5-ba94-318b8d9e54ce.png)

2022-11-15 21:24 UTC, FatimaGharsallah approved these changes

2022-11-15 21:29 UTC, merged