Transformation en Excel
CHUMneuroepilepsie/VR_Polytechnique pull request #48
Opened 2022-11-29 06:05 UTC by lulubou

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:

Transformation des informations d'un patient dans un fichier Excel à la suite de l'appui d'un bouton par l'utilisateur.

2022-11-29 06:06 UTC, lulubou commented
Pour l'instant, seulement la lecture des données fonctionne, je ne suis pas capable d'importer une librairie sans erreurs

2022-11-29 16:44 UTC, lulubou commented
Tout est complété pour la sauvegarde en CSV, peut s'ouvrir dans un classeur Excel. Sauvegarde commandée par un bouton dans le ProfilePanel.

2022-11-29 21:59 UTC, lulubou commented
Ressemble à ça dans Excel :
<img width="577" alt="image" src="https://user-images.githubusercontent.com/80421345/204657599-30dd7990-8ae5-4412-bb43-a23080fea07c.png">

2022-11-29 22:04 UTC, 4rnaudB requested changes
Il faut que l'utiliseur puyisse choisir où est téléchargé le fichier (ils ne vont pas savoir le trouver dans AppData). Aussi, il serait bien que le bouton de sauvegarde apparaisse seulement si unId est sélectionné (même si c'est vérifié dans le script).  Pour ça tu peux juste copier ce que je fais avec le bouton modify dans ProfilePanel.cs.

2023-01-16 00:49 UTC, 4rnaudB reviewed
Les paths n'existent pas pour moi et le pop up offre le path du projet en premier. Serait mieux que le défault soit le home path. Aussi le système de sauvegarde utilisé est celui par défault de unity. Serait mieux d'utiliser notre système de sauvegarde pour rester constant et éviter les confusions.

2023-01-16 00:49 UTC, 4rnaudB commented on VR_Polytechnique/Assets/Scripts/MenuScripts/FolderPanel.cs
> +        if (sceneCount == 1)
Pourrait pas être un bool à la place?

2023-01-16 00:49 UTC, 4rnaudB commented on VR_Polytechnique/Assets/Scripts/MenuScripts/FolderPanel.cs
> +            PlayerPrefs.SetString("CSV_path", BasePath);
Mieux d'utiliser notre mode de sauvegarde

2023-01-30 22:27 UTC, 4rnaudB approved these changes
Serait bien que le répertoire par défault soit le `home directory`, mais fonctionne bien maintenant

2023-02-01 06:28 UTC, merged