Positionnement des checkpoints et mauvais chemin dans la scène mode évaluation
CHUMneuroepilepsie/VR_Polytechnique pull request #50
Opened 2022-11-29 23:02 UTC by YassineDiouri1

### Checklist

- [X] J'ai donné un titre significatif
- [X] J'ai décrit la modification
- [X] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
Ajout des GameObject et script nécessaire pour ajouter la fonctionnalité des checkpoint dans la scène ModeEvaluation

2022-11-29 23:04 UTC, YassineDiouri1 commented
Les anciens checkpoints dans les prefab n'ont pas été touché. vous pensez c'est mieux de garder les objets checkpoint/WrongPath dans la scène ou vous voulez les avoir dans les prefab séparée par la suite

2022-11-29 23:21 UTC, 4rnaudB commented
Ne pourra pas être review pour demain, c'est correct?

2022-11-29 23:46 UTC, YassineDiouri1 commented
> Ne pourra pas être review pour demain, c'est correct?

Oui oui, on montrera sur la scene séparé les checkpoint all good

2023-01-15 12:36 UTC, YassineDiouri1 commented
@4rnaudB Quand tu fais la review est ce que tu pourrais passer à travers un checkpoint avec le casque VR.  C'est pour check si le message se situe à une bonne distance pour qu'on le lise bien avec tout les éléments encombrant de la forêt, la vue game dans unity est pas forcement la même que celle avec le casque

2023-01-16 01:01 UTC, 4rnaudB commented
![image](https://user-images.githubusercontent.com/55560824/212577653-0b215d38-fd89-4b1b-aeaf-859377d5b352.png)

2023-01-16 01:02 UTC, 4rnaudB commented
Le message est trop proche mais je ne le trouve pas pcq tu ne l'as pas mis dans tous les checkpoints. Je mettrais le message deux fois plus loin.

2023-01-16 20:45 UTC, YassineDiouri1 commented
Ça devrait être bon maintenant

2023-01-17 20:24 UTC, 4rnaudB commented
Peux tu regarder #52, je pense c'est mieux d'utiliser le même objet pour tous les message au jouer. Donc si tu peux review (s'assurer que rien ne bug) après je peux merge et tu pourras pull main dans cette branche pour que le code soit plus clean. (J'ai débuté un script Player pour regrouper les fonctions reliées au joueur).

2023-01-27 23:28 UTC, YassineDiouri1 commented
J'ai sauvegardé au bon endroit mais pour le temps j'ai pas reussi a le faire je sais pas pourquoi j'ai pourtant pris à partir du timer je comprend pas pourquoi ca fonctionne pas. J'ai ajoute le nombre d'erreur. Mais ils sont pas encore dans les données enregistré. Aussi je sais pas si c'est juste moi mais le menu pause fonctionne plus avec echap.

2023-01-30 03:14 UTC, YassineDiouri1 commented
@4rnaudB tu peux review quand tu as le temps

2023-01-30 23:03 UTC, 4rnaudB requested changes
* Tu peux simplement utiliser la classe Player pour attribuer l'objet Player et ensuite caller les fonctions (voir suggestions)
* J'ai pas l'impression que ton code prends en considération le niveau choisit (les 18 checkpoints sont sauvegardés) 
* L'information dans le fichier .json est affiché bizarrement (chaque valeur a son index dans le même dictionnaire?) 
* Quand je passe dans un mauvais checkpoint j'ai leur d'object assertion (l'objet teleporter n'a pas d'objet attribué)

2023-01-30 23:49 UTC, YassineDiouri1 commented on VR_Polytechnique/Assets/Scripts/MenuScripts/PauseMenu.cs
> +        playerScript.ShowPauseMenu();
je vais changer comme avec tes suggestions,en considerant le niveau choisi, pour la manière de save les checkpoint, j'ai associé un numero a chacun des checkpoint avec vrai ou faux pour dire qu'ils ont été passé ou pas, si c'est pas clair je peux les séparer un par un. je vais voir ce que tu veux dire pour les teleporteurs je suis pas sur de comprendre vu que j'y ai pas touché

2023-01-31 00:11 UTC, 4rnaudB commented on VR_Polytechnique/Assets/Scripts/MenuScripts/PauseMenu.cs
> +        playerScript.ShowPauseMenu();
Je comprends comment le données sont sauvegardées et tout c'est juste que les `keys` reviennent pour chaque info sauvegardée du même checkpoint:
![image](https://user-images.githubusercontent.com/55560824/215625356-80a85657-94f4-41c4-ac6a-7a4f2f4e8bc2.png)
![image](https://user-images.githubusercontent.com/55560824/215625374-8c091b7e-cd1f-4ef7-9421-07ddc991a52e.png)

2023-01-31 00:37 UTC, YassineDiouri1 commented on VR_Polytechnique/Assets/Scripts/MenuScripts/PauseMenu.cs
> +        playerScript.ShowPauseMenu();
Oooh ok jcomprend d’ou la confusion viens, les keys, 1..18 correspondent aux checkpoints, le checkpoint1 que tu vois c’est dans la scene check point vu qu’il y en as un il apparait aussi et son id c’est checkpoint1

2023-01-31 00:57 UTC, 4rnaudB commented on VR_Polytechnique/Assets/Scripts/MenuScripts/PauseMenu.cs
> +        playerScript.ShowPauseMenu();
Ouais je comprends, mais pourquoi la première `key` c'est Checkpoint 1?

2023-01-31 01:03 UTC, YassineDiouri1 commented on VR_Polytechnique/Assets/Scripts/MenuScripts/PauseMenu.cs
> +        playerScript.ShowPauseMenu();
Ooh c’est car y’en a un dans la scene checkpoint so il l’affiche, je vais la supprime je l’avais oublié

2023-01-31 21:25 UTC, YassineDiouri1 commented
@4rnaudB j'ai effectué les modifications. 

- Pour le script j'ai laisse le Player en private et je le récupère directement avec une ligne de code, mais j'ai mis directement le component au lieu du gameobject. Ca évite de devoir drag 18 fois le player et ca fait la même chose. J'ai enleve playerScript comme dans tes suggestions.
- Pour les différents niveau, j'ai ajouté cela, seul problème que je n'ai pas reussi a resoudre c'est si tu commence par faire le niveau 1, puis que tu fais un niveau qui a plus de checkpoints, les données seront pas bien ordonné du plus petit au plus grand. mais elle sont toutes la. 
-  J'ai laissé comment les valeurs étaient affiché, et retiré le Checkpoint 1. Je pense que c'est mieux de les laissé comme ca sinon ca va etre beaucoup trop lourd en terme d'affichage. faut qu'on voit comment ca sort sur excel pour décider comment on les gardes.
- L'erreur quand tu prend le teleporteur devrait avoir été corrigé.

2023-01-31 23:57 UTC, 4rnaudB reviewed
Les valeurs dans settings ne sont pas modifiées et le message d'erreur n'apparait pas/si tu es en mouvement il disparaît tout de suite.

2023-02-01 21:47 UTC, 4rnaudB commented
De mon bord ça ne sauvegarde pas dans le fichier settings

2023-02-02 16:45 UTC, YassineDiouri1 commented
> 

C'est bizarre ca fonctionne bien chez moi, que ce soit en passant par le menu ou directement par la scene, est ce que tu fais quelque chose de particulier ?

2023-02-06 15:50 UTC, 4rnaudB commented
Fonctionne pas tout le temps,peut-être tu ne sauvegarde pas dans le json après chaque checkpoint? Si oui c'est correct mais pour tester ça veut dire qu'il faut se rendre au menu de fin. Aussi si tu peux merge le main dans ta branche pour tester pcq le jeux bug beaucoup avec ta version du main.

2023-02-09 22:38 UTC, YassineDiouri1 commented
@4rnaudB j'ai fait les changements pour les nouvelles info à sauvegarder, mais quand j'ai pull le main ca a rien change dans la scene ModeEvaluation et ca me dit already up to date quand je l'ai refait.
Je sais pas trop ce qui fait ca...

2023-02-11 19:48 UTC, 4rnaudB commented
* J'ai l'erreur suivante à l'ouverture du mode évaluation:
![image](https://user-images.githubusercontent.com/55560824/218277660-2cdda73e-a39c-43d7-b58c-0ce49f9513e4.png)

* Il y a un checkpoint avec un wrongPath en enfant placé à la même position
![image](https://user-images.githubusercontent.com/55560824/218277628-54702075-2460-43e4-bf6e-55bb793cf539.png)

* Après avoir passé les deux premiers checkpoints de la zone LG, aucun n'a été sauvegardé (j'ai aussi traversé deux mauvais chemins)
![image](https://user-images.githubusercontent.com/55560824/218278137-963f8c45-b6ae-4a4f-a5eb-0f9e118241bb.png)

* Les messages lorsqu'on se trompe de chemin fonctionne, mais le mouvement n'est pas arrêté pendant une ou deux secondes

* Je ne suis plus capable d'accéder au Menu Fin, selon l'erreur (Menu_Fin_ doesn't exist) on dirait que la langue n'est plus accédée par le menu pause

2023-02-13 02:40 UTC, YassineDiouri1 commented
Les noms des Wrongpath à sauvegarder sont pas encore au point, je suis toujours dessus.

2023-02-13 20:49 UTC, YassineDiouri1 commented
@4rnaudB Ca save bien toutes les information maintenant. il reste deux truc dont je suis pas trop sur :
- je sais pas trop comment stop le player pendant 2 sec car  Time.timeScale = 0 puis =1 fonctionnerai pas car il y a le delay au milieu donc  si tu as une idée de comment faire.
- Est ce que tu pourrais check si timeGoodPath de ton coté se save correctement dans certain de mes essai sur niveau 1, 12 checkpoint, il save quand meme jusqu'a 18 au lieu de 12 et je sais pas d'ou ca viens car ca se fait comme pour les autres info.

2023-02-15 21:15 UTC, EmmanuelDW commented
Yassine : Tout fonctionne, le joueur est arrete quand il prend un checkpoint jusqu'a ce qu'il appuie sur le trigger de la manette gauche, tu peux tester live sur clavier je l'ai bind à Z sur le clavier quand tu aura test et valide fait moi signe pour que je merge avec le nouveau main ( ou fait le si tu veux ca me derange pas )

2023-02-16 00:54 UTC, YassineDiouri1 commented
@4rnaudB oublie de te mentionne

2023-02-17 23:01 UTC, 4rnaudB commented
* Ça sauvegarde bien le Wrong_path, mais les autres données ne sont pas sauvegardées pour moi
* Un fichier Evaluation_Results est créé hors des dossiers des patients
* Tu peux merge le main actuel, ça va être plus facile de tester

2023-02-17 23:10 UTC, YassineDiouri1 commented
> * Ça sauvegarde bien le Wrong_path, mais les autres données ne sont pas sauvegardées pour moi
> * Un fichier Evaluation_Results est créé hors des dossiers des patients
> * Tu peux merge le main actuel, ça va être plus facile de tester
- weird, on avait tester l'autre j avec lucas et ca fonctionnait bien
-Est ce que tu lance dans mode évaluation puis tu save en passant par le menu, j'ai eu la même chose aussi mais si tu le fais normalement en passant par le menu ca marche normalement,

2023-02-18 15:09 UTC, 4rnaudB commented
J'ai essayé sans menu et avec menu

2023-02-20 00:12 UTC, ReiherL commented
@4rnaudB main merged et les modification on été faites, pour test les différents niveau faudra te déplacer a la main vu que ya pas les bonnes coordonnées dans le script de position de départ

2023-02-20 15:10 UTC, 4rnaudB approved these changes

2023-02-20 15:43 UTC, merged