Interactions joueur-objet prêtes pour test
CHUMneuroepilepsie/VR_Polytechnique pull request #52
Opened 2023-01-11 23:05 UTC by gabygabou

### Checklist

- [x] J'ai donné un titre significatif
- [x] J'ai décrit la modification
- [x] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:

Lire les commentaires dans le script "Disappear.cs", les modifications / fonctionnalités du code y sont détaillées. Le prefab "Player" et un "Locomotion System" ont été ajoutés à la scène "Test_Prise_Objet" pour pouvoir tester le script directement dans cette scène. Le gameObject auquel le script est rattaché est un cube nommé "Cube" et, lorsque l'objet est ramassé, un texte apparait à l'écran (objet texte nommé "Text (TMP)" sous Canvas dans Hierarchy).

@4rnaudB

2023-01-13 20:04 UTC, 4rnaudB requested changes
Pas adapté au VR

2023-01-16 00:37 UTC, 4rnaudB commented
voir #53

2023-01-17 00:12 UTC, gabygabou commented on VR_Polytechnique/Assets/Scripts/Disappear.cs
> +    }
Corrigé avec le dernier commit

2023-01-17 00:12 UTC, gabygabou commented on VR_Polytechnique/Assets/Scripts/Disappear.cs
> +
Corrigé avec le dernier commit

2023-01-17 00:12 UTC, gabygabou commented on VR_Polytechnique/Assets/Scripts/Disappear.cs
> +            // et Axis1D.SecondaryIndexTrigger pour manette droite)
Corrigé avec le dernier commit

2023-01-17 00:12 UTC, gabygabou commented on VR_Polytechnique/Assets/Scripts/Disappear.cs
> +                    {
Corrigé avec le dernier commit

2023-01-17 00:13 UTC, gabygabou commented on VR_Polytechnique/Assets/Scripts/Disappear.cs
> +   // }
Corrigé avec le dernier commit

2023-01-19 18:25 UTC, closed without merging