ajout du lac
CHUMneuroepilepsie/VR_Polytechnique pull request #55
Opened 2023-01-20 22:54 UTC by andrea-s1

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
J'ai ajouté le lac (modification du relief du terrain, ajout d'un plan d'eau, importation d'un shader). J'ai aussi dû modifier la végétation aux alentours pour que ça match avec la présence du lac.

2023-01-22 22:59 UTC, FatimaGharsallah requested changes
Tu n'as pas mis de "material" à ton eau donc elle est rose par défaut. 
![image](https://user-images.githubusercontent.com/80424041/213944933-2fc8f83d-7acd-4ea3-b2f8-0c75cc172577.png)
Je ne vois pas non plus le dossier qui est associé au asset. Est-ce qu'il y en a un ?

2023-01-23 00:06 UTC, andrea-s1 commented
@FatimaGharsallah  Oh c'est bizarre, pourtant j'avais appliqué le shader et tout était beau pour moi quand j'étais dans Unity... Je checkerai ça mardi!

Pi pour le dossier de l'asset, techniquement il devrait y en avoir un, mais je me rappelle plus si c'est un "asset" à proprement parler, donc peut-être qu'il se trouve quelque part d'autre. Mais en gros le "material" de l'eau c'est un "shader".  Peut-être que c'est un des fichiers que je n'ai pas commit et que j'aurais dû... à voir!

2023-01-26 16:51 UTC, FatimaGharsallah commented
@andrea-s1 c'est good, on voit l'eau maintenant. Par contre, quand j'ouvre ta branche j'ai deux erreurs qui sortent par rapport aux fichiers importés. Essai de regarder ça.
![image](https://user-images.githubusercontent.com/80424041/214897270-617c41e8-401c-41af-848a-4a848367523e.png)

Aussi, mets tous les dossiers importés en lien avec le design dans le dossier Design et enlève tous les fichiers inutiles pour le lac (ça prend de la place pour rien).

2023-02-27 21:25 UTC, 4rnaudB commented
J'ai les erreurs suivantes et c'est encore l'ancien monde.
![image](https://user-images.githubusercontent.com/55560824/221688923-bfe3e329-e3de-4bbe-860c-8eb2f8f3a705.png)

2023-03-02 23:47 UTC, andrea-s1 commented
@4rnaudB Ouais finalement jpense qu'on va laisser tomber cette branche (à valider mercredi), parce qu'on va probablement utiliser le nouveau monde, donc plus besoin de faire un lac pour ce monde...

2023-03-03 16:15 UTC, closed without merging