Spawners
CHUMneuroepilepsie/VR_Polytechnique pull request #72
Opened 2023-02-14 21:10 UTC by 4rnaudB

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
* Copie de la scène Moide_Évaluation dans Mode_apprentissage + ajout des spawners
* Fix pour #71 
* Déplacements des fichiers terrains d'EDW dans Assets/Terrains/EDW_Terrains

2023-02-14 21:11 UTC, 4rnaudB commented
@EmmanuelDW voir PR pour l'emplacement des fichiers terrains que tu as ajouté dans #68.

2023-02-16 00:08 UTC, FatimaGharsallah requested changes
Les spawners S1-3 sont avant le point de départ et les spawners S13 S18 S19 S24 S27 S39 S40 S50 S52 sont positionnés dans les mauvais chemins, donc le patient ne va jamais voir les objets (il faudrait les repositionner). Aussi, le message d'avertissement pour retourner au menu principal n'est pas le même que celui pour quitter, est-ce qu'on veut les uniformiser ou non ?

2023-02-17 22:13 UTC, 4rnaudB commented
Oui les spawners dans les mauvais chemins c'est pcq j'ai oublié qu'ils avaient des panneaux pour leur donner le chemin alors je ne voulais pas qu'ils utilisent la présence d'objets pour se diriger.

2023-02-17 22:41 UTC, 4rnaudB commented
Pour le message ce n'est pas très important, dans les deux cas l'utilisateur quitte la scène Menu_Fin donc deux messages identiques est correct selon moi.

2023-02-17 22:43 UTC, EmmanuelDW commented
Est-ce que ca peut causer problème si un spawner est l'autre côté d'un mur invisible (avec le pick up des objet)

2023-02-17 22:45 UTC, 4rnaudB commented
J'imagine pcq le raycast doit frapper le mu invisible?

2023-02-17 22:46 UTC, 4rnaudB commented
@EmmanuelDW si c'est le cas je pense que c'est mieux de reculer les murs un peu pcq je n'ai pas mis les objets très loin et je ne voulais pas tous les mettre dans le chemin.

2023-02-17 23:11 UTC, EmmanuelDW commented
Est-ce que tu veux que j'attende après le merge pour le faire?

2023-02-18 15:08 UTC, 4rnaudB commented
Dérange pas, tu peux te créer une branche à partir de celle-ci (git checkout -b en étant dans cette branche aussi) si tu préfères travailler mtn.

2023-02-18 19:01 UTC, FatimaGharsallah approved these changes
Looks all good!

2023-02-18 21:13 UTC, merged