ajout fleurs et buissons sur terrain lau
CHUMneuroepilepsie/VR_Polytechnique pull request #75
Opened 2023-02-16 20:47 UTC by ReiherL

### Checklist

- [ ] J'ai donné un titre significatif
- [ ] J'ai décrit la modification
- [ ] J'ai donné à cette demande la bonne étiquette

### Description de la modifications: ajout des fleurs le long du chemin.

2023-02-17 16:58 UTC, EmmanuelDW approved these changes
Bonne densité et tout. Il dra juste en ajouter un peu au début des chemins qui sont pas bon pour que ca soit pas trop évident (dans le futur).

2023-02-18 19:37 UTC, FatimaGharsallah requested changes
Tu as plein de fichiers terrain_data, c'est quoi ? C'est utile? Si non tu deleteras stp!
![image](https://user-images.githubusercontent.com/80424041/219884871-c12f5d6f-ad31-4b99-925c-959dc2c4b147.png)

2023-02-20 02:43 UTC, FatimaGharsallah approved these changes
Finalement, on a dit que c'est correcte ces fichiers.

2023-02-20 14:59 UTC, ReiherL commented
@FatimaGharsallah Jsp d'ou ils viennent ces fichiers, mais ils créent des conflits

2023-02-20 15:04 UTC, merged