Ramake du lac
CHUMneuroepilepsie/VR_Polytechnique pull request #78
Opened 2023-02-18 19:40 UTC by EmmanuelDW

### Checklist

- [x] J'ai donné un titre significatif
- [x] J'ai décrit la modification
- [x] J'ai donné à cette demande la bonne étiquette

### Description de la modifications:
J'ai refait le travail de la branche EDW/ShaderLac parce que les assets no utilisé ne voulaient pas se faire retirer.

2023-02-18 19:45 UTC, FatimaGharsallah requested changes
Transfert le dossier du asset du lac (A.U.R.W) dans le dossier Design stp! Et c'est quoi tous les fichiers terrain_data?
![image](https://user-images.githubusercontent.com/80424041/219885170-cf124096-e7fd-4872-9101-4bc73293dea4.png)

2023-02-18 19:51 UTC, EmmanuelDW commented
C'est fait pour le transfert, les terrain data cest le relieft des terrains. Si on veut les mettre dans un fichier il faudrait le faire quand il a pas de branche design active pour éviter les problèmes.

2023-02-18 21:14 UTC, 4rnaudB commented
Ça a été fait dans ma branche. Tu peux juste les deletes dans la tienne.

2023-02-18 21:45 UTC, EmmanuelDW commented
Je suis un peu confused parcec que j'ai merge le main dans ma branche et j'ai rien eu à resolve

2023-02-19 21:55 UTC, 4rnaudB commented
Oui c'est normal

2023-02-20 16:11 UTC, EmmanuelDW commented
J'ai merge le main dans ma branche à nouveau, les conflits devraient être resolved

2023-03-08 02:35 UTC, FatimaGharsallah approved these changes

2023-03-08 02:36 UTC, merged